#!/usr/bin/with-contenv /bin/bash

if [[ ! -z "${PUID}" && ! -z "${PGID}" && ! -z "${PUSERNAME}" ]] && ! &>/dev/null id "${PUSERNAME}"; then
  shell="$(which bash || which sh)"
  addgroup --gid "${PGID}" "${PUSERNAME}"
  adduser --home "/home/${PUSERNAME}" --shell "${shell}" --gid "${PGID}" --uid "${PUID}" "${PUSERNAME}"
  chown -R "${PUID}:${PGID}" "/home/${PUSERNAME}"
fi

